### ISSUE TITLE
Tips on HTTPS output

### ISSUE THREAD

**Issue by alexbarbato** [tsalm-pivotal/tap-install#10]
Any thoughts on making the CNR config option in the Tips section a post-install script or even trying to inject it into the install script itself?

Not sure if anyone wouldn't want that configured as you stated

https://github.com/tsalm-pivotal/tap-install#tips

**Comment by alexbarbato** [comment]
Actually the guide as written just gets wiped with kapp so maybe we are just waiting for this to be supported in the package install config.

**Comment by alexbarbato** [comment]
I'll be really interested to see how you implement this considering we are currently using the "tap" package install, but talking about configuring the underlying CNR package, but I'm also not a Carvel pro!

You'll be teaching me by showing it

**Comment by tsalm-pivotal** [comment]
https://github.com/tsalm-pivotal/tap-install/commit/2c0e1dd348c97302cf506e437767f0f536058edd
