### ISSUE TITLE
TAP 1.0.1

### ISSUE THREAD

**Issue by alexbarbato** [tsalm-pivotal/tap-install#7]
Do we want to update the various TAP install versions to 1.0.1 now that it's out?

Thought about making a PR, but didn't know if there was a reason to want to be at 1.0.0

**Comment by tsalm-pivotal** [comment]
Did it based on the documentation: https://github.com/tsalm-pivotal/tap-install/commit/d2ae8846624479fdfa80d8622057c1c2e3510823
 Will validate it in the next few days.
